### ISSUE TITLE
Feature request: Add whitelisting errors list and exit if new error occured

### ISSUE THREAD

**Issue by omer-za** [microsoft/infersharpaction#40]
I want to have the ability to provide whitelist patterns and filter them from results,
then if a new issue popped out it will fail on exit code 1.

**Comment by xinshiMSFT** [comment]
Great suggestion! It may be a bit difficult to achieve as the host needs to have knowledge of previous runs. We are looking at a local incremental analysis capability which Infer# will only analyze on the changed files/binaries.

Your thoughts on filtering results based on patterns is definitely interesting. We will look into it more. Thank you!

**Comment by xinshiMSFT** [comment]
[SARIF was added to v1.2.1](https://github.com/marketplace/actions/infersharp?version=v1.2.1), which GitHub Advanced Security has very nice support for viewing and managing alerts. You can [dismiss an alert](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#dismissing-or-deleting-alerts), so that next time code scanning runs, the same code won't generate an alert.

**Comment by omer-za** [comment]
Great feature, right now I don't have GitHub Enterprise so that I can't really use it but it might be useful in the future.
